//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Auto-service_" +
            "DB.mdf;Integrated Security=True")]
        public string Auto_service_DBConnectionString {
            get {
                return ((string)(this["Auto_service_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\bin\\Debug\\Aut" +
            "o-service_DB.mdf;Integrated Security=True")]
        public string Auto_service_DBConnectionString1 {
            get {
                return ((string)(this["Auto_service_DBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-F2RINTF\\SQLEXPRESS;Initial Catalog=C:\\USERS\\SEREG\\SOURCE\\REPO" +
            "S\\БАЗА_ДАННЫХ\\БАЗА_ДАННЫХ\\AUTO-SERVICE_DB.MDF;Integrated Security=True")]
        public string C__USERS_SEREG_SOURCE_REPOS_БАЗА_ДАННЫХ_БАЗА_ДАННЫХ_AUTO_SERVICE_DB_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_SEREG_SOURCE_REPOS_БАЗА_ДАННЫХ_БАЗА_ДАННЫХ_AUTO_SERVICE_DB_MDFConnection" +
                    "String"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-F2RINTF\\SQLEXPRESS;Initial Catalog=Auto_Service_DB;Integrated" +
            " Security=True")]
        public string Auto_Service_DBConnectionString2 {
            get {
                return ((string)(this["Auto_Service_DBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-GS814L6V;Initial Catalog=Auto_Service_DB;Integrated Security=T" +
            "rue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string Auto_Service_DBConnectionString3 {
            get {
                return ((string)(this["Auto_Service_DBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Properties\\Da" +
            "taSources\\Auto_Service_DB.mdf;Integrated Security=True")]
        public string Auto_Service_DBConnectionString4 {
            get {
                return ((string)(this["Auto_Service_DBConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Data\\Auto_Ser" +
            "vice_DB.mdf;Integrated Security=True")]
        public string Auto_Service_DBConnectionString5 {
            get {
                return ((string)(this["Auto_Service_DBConnectionString5"]));
            }
        }
    }
}
